### ISSUE TITLE
site: general TODO + dicussions

### ISSUE THREAD

**Issue by thibaultCha** [Mashape/kong#5]
Currently @rainum and me are partially on the website, and @thefosk is writing the documentation.

Both will need to be reviewed.

TODO list:
- [ ] 404 Page #43 
- [x] Landing page
- [ ] Benchmarking "blog post"
- [x] Contribute page
- [ ] Support page
- [ ] Plugins page
- [ ] Download page
  - [ ] Download instructions for each platform
  - [x] Subscribe form
- [ ] Docs
  - [ ] Tutorials
  - [x] Screencats
- [ ] Remove alpha banner

**Comment by thefosk** [comment]
@ahmadnassri can join us on this too

**Comment by ahmadnassri** [comment]
> @ahmadnassri can join us on this too

just assign me things as you see fit.

**Comment by thibaultCha** [comment]
It's just for discussion

**Comment by thefosk** [comment]
Let's review the entire website when `0.1.0-beta` has been released and the plugins, download and support pages have been fully implemented.
